project:
  type: website

website:
  title: "Guides de démarrage"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: 01_r_et_rstudio.qmd
        text: R et RStudio
      - href: 03_google_colab.qmd
        text: Google Colab

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    lang: fr
    link-external-newwindow: true