project:
  type: website

website:
  title: "Guides de démarrage 2026"
  navbar:
    title: false
    logo: images/00_logo_rqrad.png
    logo-alt: "Logo du projet"
    left:
      - href: index.qmd
        text: Accueil
      - href: 01_r_et_rstudio.qmd
        text: R et RStudio
      - href: 02_github-codespaces.qmd
        text: GitHub Codespaces
      - href: 03_google_colab.qmd
        text: Google Colab
      - href: 04_anaconda_miniconda.qmd
        text: Anaconda et Miniconda
      - href: 05_spyder.qmd
        text: Spyder

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    lang: fr
    link-external-newwindow: true
    lightbox: true